language: node_js
node_js:
- 6.9.2
env:
  global:
  - CXX=g++-4.8
  - secure: "l1msXauoKxq0/pesOZu50d6TjlzV3+fq72JjFNDAcgmr9qE7Ck4/MkjV+RQC3w09aqGajLvTpph+OJgblW8aVbtjPSK2PN1qDqL040x2PlT5GbsWuWqm/R+kBnS26sCZKhdgYpjyxKN5f0FjCh3UYvbMkH6pGjg8heP5NDN1ujvC1vkxIf/beI6RuhhqM7L4HjG1evRAsvgW7bGkyymjIsfrdctvJCnGLVS8D0zvDnZ0YEepPvPek0bzuyu6K9J4RAuIIuihas55nKzXqCY8HA2DGdTnxE4RAgC5LQNZJzx5aPUwmr9wxHXjLxqy7/KUNyD1DOJBKQtoFpUDXMZ8Lamvnkta3jLOLQDQzjCq0ySqQG4lrBWy6VFmrshY04X/FcL4PjffLJgWubQANacSsbjb1107yRJS6AWGJZjUSFf8Fpam7SkgdLmfMiMNkWibflJMF+9sZGpalXVhUFF+pLnN/1sRt0D1V8zfuTATn/R6nb2yPd0+F07749Y+uRdklU8Fl6296YZ6vZ9zxGsPVEv1v3hVADxnEETbONVKfqzWCQvQMvrdrxLia98Bi+g5HejLwPEkBB/2+MzGtodn/ETVVxRsnLI3qBFIU2WvwVrYONxW4/FZfQY+om9sD/mS+TSJ3MPmCl81GY66if/WxOq75uEf469wAjOB5wB6CV8="
  - secure: "Ld7OVJgFHBbeWnmJ70nYTG+oSmp0zdHnEVz9S9abwWpcafCm7FHOEM1B3O4isJQ3qvjsbr7sJ5nVhkGFcs0yiHjTmKjfw3i947dYNJhEUnx5HfTGPBRwMz7kP6t1/rkxYAS07C1a2/JI0a35R/gDxA7eW0MQLtejCRSFCaF7/hjTfCLdkD7yv2Jh144Rd7ognQVy6AgqeeO7L4oujT4q1TwlzG8cksZhRPfOwuenkShYvtugYzF4/f7sK+AO+g2xeuaGorQV6wXLFdiCq8Pm5ZKl1Ljy0zS+SFgALaf64WnyecX/KO/uIFTydvFjem25zFvOjpviSABM6l7DAOWen0v74PIou/WCnVtliCV+bM5vtgZzBXMFHkD8Ll0r9jyhTsH833pkf+YNQXNT82a10JKkJT6XzBGvwRHHcjurxZUA18ad1BQHY3JvgYqeIUF+mjb8t++bTckUxRG+4tQU7Crb2FL6u1AmjWxQPt7leubGScZZLwXOK/tOiCZJJW+rcoG72O03fxjEA/QVh7YuyZajceYJXVxHmWA1RT3wksf9/DnEt6QWQoRT8xEOXjcfKSMesFONjnpcGHxrcf0mjHxfKdDE8WQi9N7heaD/ASPmq0jpdn7+q8qGY3iOKgPELdN4xp+IIX4eC/FQhLEq4A07O9JXdfw9gTA8gHwkAaI="
  - secure: "xybeo1gtLLkDZ8RrOTaJZj+MP9Eo5fttKxGlIsSKNMKdOTEIZ5W8xDkcpIHywjEPLLYlms0sjSu5rjUPT7j1DXIee3qUQAhWeAWEZlQWzK1ku29h/A0tXb1cFgHdkwGSqxrTqpdj/RTYISTfFLLGqclYbrUi/eBQi+MKwTz5JgbrcJuA62hZ1oWeHhkRrm14GVrCte1Z7/B2VM6AbBLhCc8I648KPKkRMeH1sLm3N0eQYoTy0dYmRzwvlIEzhP9gZAjUgwDRXrU2oi0kHhan+fDZ2XSs/EXxpSNbd6tl/vPCVGj3LuDCowPLmuWBpaN+lmk1QTUIPXuB4+3dMbt/sLmmXy9ZjhzA215zh/NuRYDkXrKlYxM4AVzLjDsRsLkj+7jvg+wVUpCemJW9QDt0RAzaxa1iJDhRa8J90ns69Wo5Z+j1sR3WRiZj6ii0Bu/qwSrw9nSrv8Am+IIxRNNR3SIx/C715Pezkr7s1K0Pjl9D2qxE45s4+sgqF6TiPoLbWAoc3zPJ1V57j2J9SanBZFkALPKfdfHzXF91L7IxfD4X3WNuQx5qdEZvJw2Nnp9/ndEq5yLxf3CxIhXPRR6fiMlvqNzDqM1ShdPO2g5MHAXKR3dkcet/8DU4SU5aS17YYmQTHK1X89NwkOwYzY9DJeo+5+Ip4PAzHJ8s9M84cpc="
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: false
install:
- npm install


script: npm test